### ISSUE TITLE
Bluetooth Battery Usage

### ISSUE THREAD

**Issue by ItamiWasTaken** [GrapheneOS/os-issue-tracker#1050]
![Screenshot_20220310-191147](https://user-images.githubusercontent.com/99271684/157777064-0c95110d-ba58-407e-bd01-21cf096a9215.png)
the accuracy of Bluetooth usage is buggy

**Comment by thestinger** [comment]
Need to know your device model and OS version.

**Comment by ItamiWasTaken** [comment]
oh, my bad, Pixel 6 running Android 12

**Comment by thestinger** [comment]
@ItamiWasTaken We've released the first Android 12.1 release in the Beta channel and it will be in the Stable channel soon. There's a good chance it fixes this issue.

**Comment by ItamiWasTaken** [comment]
@thestinger I'll return back if it persists after updating to 12.1 release when it's stable

**Comment by ItamiWasTaken** [comment]
![Screenshot_20220312-153833](https://user-images.githubusercontent.com/99271684/158034223-4516e4bf-36ba-41f3-8ff9-bafa7f36d85d.png)
this issue persists even after updating to 12.1

**Comment by thestinger** [comment]
Please check if this is fixed on the latest release ([2022032110](https://grapheneos.org/releases#2022032110)) due to multiple battery usage stat fixes.

**Comment by flawedworld** [comment]
Let us know if this is still an issue please.
