### ISSUE TITLE
Visual voicemail not activating

### ISSUE THREAD

**Issue by reitenth** [GrapheneOS/os-issue-tracker#1108]
I just installed grapheneos and everything was working fine. I am using a Pixel 4a with Verizon as my carrier. Whenever I activate visual voicemail in the phone settings, there is a banner at the top of the voicemail tab that says, "You might not receive voicemail notifications until visual voicemail is fully activated." Any help would be appreciated.

**Comment by thestinger** [comment]
> I just installed grapheneos coming from calyxos and everything was working fine. I am using a Pixel 4a with Verizon as my carrier. Whenever I activate visual voicemail in the phone settings, there is a banner at the top of the voicemail tab that says, "You might not receive voicemail notifications until visual voicemail is fully activated." Any help would be appreciated.

Does it work despite the warning, or does it not work?

**Comment by reitenth** [comment]
it does not work at all. no new voicemails show up and I still have to call *86.

**Comment by OpenSourceGhost** [comment]
I have the same issue with T-Mobile. It used to work just fine on Graphene OS, but stopped working about 1 month ago (or so).  I thought it was VPN-related, but the same issue persisted when I disabled VPN.

**Comment by flawedworld** [comment]
So far I have confirmed there is some form of issue on Verizon USA, despite previously working.

The Ting MVNO (on T-Mobile USA) seems to be working fine though.

O2 UK seems to be not working, but I don't know if it has ever worked.

**Comment by BalooRJ1** [comment]
Visual Voicemail stopped working for me as well about a week or two ago. I am using a MVNO carrier named Mobi that uses the Verizon network.

**Comment by PJK2011** [comment]
I tested this issue today. Pixel 5a. Google free owner profile and Google compatibility profile. T-Mobile SIM. Visual Voicemail activated in both scenarios. 

In owner profile voicemail is seen in the screen background, but the app cannot be used because it's covered with a dialog box stating that the app can't be used because it requires play services. 

Curiously I can play the voicemail if I tap it in the notification shade. The app again covers with the dialog box. The box has only one button, Install. Of course nothing happens when tapping install. 

In the compatibility profile, I can launch the app and select the voicemail. In the list of voicemails, the correct length of the voicemail shows, but after selecting the voicemail, it opens a screen with the playback controls, but the length displays as zero and nothing happens when you tap play. 

You can slide the progress marker to the right, but it snaps back to the beginning since the length is zero. This screen is also unstable with the notification bar at the top flashing, the controls being largely unresponsive. 

I attribute these behaviors to a defect in the compatibility layer. I do not log into Google.

**Comment by flawedworld** [comment]
>I attribute these behaviors to a defect in the compatibility layer.

It's nothing to do with it.

**Comment by flawedworld** [comment]
For anyone who cannot be bothered to wait for a fix, you can use Google Dialer + sandboxed Google Play to get working Visual Voicemail for now.

**Comment by PJK2011** [comment]
> For anyone who cannot be bothered to wait for a fix, you can use Google Dialer + sandboxed Google Play to get working Visual Voicemail for now.

I see no need for a voicemail app since GrapheneOS dialer has a voicemail tab at the lower right of the screen.

**Comment by pkhomyakov-rms** [comment]
@flawedworld should google dialer work in secondary profile? It never did for me on Pixel 5a with US ATT SIM, not before, not now on latest release. The app displays main screen and then hangs, followed by "app in not responding, wait/stop" dialog. I have not tried main profile because I only have sandboxed google play in secondary.

**Comment by flawedworld** [comment]
Give it phone and sms access

**Comment by pkhomyakov-rms** [comment]
SMS/Phone are enabled automatically when you select default phone app. I gave it every permissions it lists in settings including location and media while troubleshooting. It did not make any difference for me.

**Comment by pkhomyakov-rms** [comment]
I stand corrected! I gave it SMS and Phone explicitly before selecting it as default phone app and it make it work. Thanks for the clarification!

**Comment by OpenSourceGhost** [comment]
Is this a Graphene OS bug or general Android bug or carrier/provider bug?

**Comment by flawedworld** [comment]
This is an AOSP bug likely caused by a carrier change.

**Comment by flawedworld** [comment]
Pixel 6 GB7N6 (ROW variant) confirmed to have working Visual Voicemail on Verizon USA.

**Comment by zeugmatis** [comment]
Pixel 5a on Mint (T-Mobile) getting same error "Can't activate visual voicemail".  Voicemail does seem to be working the old way (long press 1).  If replacing the GrapheneOS phone app with google dialer as suggested, will it immediately slurp up all my contacts and upload them to google (because the dialer needs access to contacts)?   

Phone is running GrapheneOS stable, updated last night but error message is still there.

**Comment by zeugmatis** [comment]
Wanted to quickly comment that an update was applied two days ago and now visual voicemail is working perfectly here.  This is on Mint (T-Mobile).  Thanks much!

**Comment by Zanthed** [comment]
Going to assume this is fixed then on the latest release 2022052500.

**Comment by reitenth** [comment]
still doesnt work for me on Verizon (which was the carrier that was having the original problem)

**Comment by BalooRJ1** [comment]
Visual Voicemail is now working for me using GrapheneOS on Mobi, which is a Verizon MVNO. It wasnt working previously. The fix fixed the problem for me.

**Comment by ilikenwf** [comment]
> Going to assume this is fixed then on the latest release 2022052500.

2022102800 here, visual voicemail and normal voicemail both are not working here. Not sure if it is a provisioning thing or what. My parents on the same carrier (Visible - Verizon) experience the same although in their case they don't even have a voicemail tab displaying in the dialer, neither stock nor google.

#1629 is my issue on this subject.

**Comment by forenoon9182** [comment]
I have the same issue. Pixel 4 running grapheneOS (fully updated with stable) Visible MVNO using verizon.
I have no voicemail button at all. It used to work just fine till about a month ago then it quit. I cannot find anything about Visual VM in the app at all, but in the past I have been able to. My wife has a Pixel 4 running grapheneOS with T-Mobile works fine there. Hers (OS) was installed about 2-3 months ago and I have been using mine for several years now.

**Comment by ilikenwf** [comment]
Since visible recently setup a second service track - esim for new people and physical for old (like me) I wonder if they've done something to screw up their configs or necessitate reprovisioning?

**Comment by Chett23** [comment]
Hi I am running build 2023052900 on a pixel 6a and Tmobile as my carrier and im having this issue as well. I tried downloading google dialer but that still didnt work even after granting all the permissions it requested. I have google services sandboxed. I removed the app and downloaded it again then granted phone, sms, and call logs before setting it as default, as @pkhomyakov-rms stated above. still nothing. and visual voicemail isnt an option in the settings of the google dialer while it is an option, but just doesnt activate in default dialer. If this is a bug in ASOP and not GrapheneOs where can I go to try yo fix this?

**Comment by trespitt** [comment]
I believe this is still happening - flashed GrapheneOS onto my Pixel 8 a week ago and visual voicemail has never worked (Mint cellular provider).
Will not be able to use GrapheneOS unless this gets fixed because I don't have time to call *86 to get all my voicemails every day

**Comment by ilikenwf** [comment]
I'm still struggling with it with Visible, but I use voicemail so little that I don't care.

**Comment by clairerichardsRN** [comment]
I am having this issue on Pixel 7a
