### ISSUE TITLE
Settings ➔ Apps ➔ Sandboxed Google Play configuration not available in Work Profile

### ISSUE THREAD

**Issue by caveman1973** [GrapheneOS/os-issue-tracker#1116]
In https://grapheneos.org/usage#sandboxed-google-play-configuration says:
"If you want to use Google's geolocation service instead, you can disable the "Reroute location requests to OS APIs" toggle"

When I go to Settings ➔ Apps ➔ Sandboxed Google Play and I click it, it opens the browser and redirects to https://grapheneos.org/usage#sandboxed-google-play-configuration

The Sandboxed Play Services are installed in my Work Profile.

**Comment by thestinger** [comment]
That's not configuration for the work profile.

**Comment by caveman1973** [comment]
So the solution for the battery draining issue (#1003) you'll need to uninstall Play Services from Work Profile and install at the Main so I can access the toggle?

Is there another way to disable the "Reroute location requests to OS APIs"?

**Comment by thestinger** [comment]
There isn't a battery draining issue. It was already resolved.

**Comment by alexmo1997** [comment]
Shouldn't this be kept open? There isn't any way to access a sandboxed google play configuration menu for the work profile, so this isn't really resolved.

**Comment by Zanthed** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/992
