### ISSUE TITLE
Alarm not working after restart

### ISSUE THREAD

**Issue by wellthissucks** [GrapheneOS/os-issue-tracker#1476]
If the phone reboots overnight, the alarm will not make any sound in the morning. Turning off the Auto Reboot feature fixes the problem. This is a fairly recent issue, as it wasn't happening before the update to Android 13 a few days ago (and they wonder why people don't like their stuff doing auto-updates). 

Pixel 4a
Build # TP1A.220905.004.2022090600
Stock Clock app.
Auto Reboot is usually set to 2 hours. Never been an issue before this update, but have not done an update for a while before this.

Tried clearing the Clock App data, and setup all alarms again. Issue continues. Makes the Auto Reboot feature useless.

**Comment by erryKinq** [comment]
Ive got the same Problem with the 4XL and since yesterday with the 6a

**Comment by wellthissucks** [comment]
So I guess the only solution for this problem is to either NOT use my phone as an alarm clock, ot NOT use the Auto-Reboot feature.

I updated the phone completely yesterday, and this issue is still there. Clearly something got changed some time shortly before I originally posted this issue, as it always worked properly before that.

**Comment by thestinger** [comment]
Apppears to be resolved.

**Comment by david-andrew** [comment]
Hi, I just had this issue this morning, so I do not think it is resolved.

Pixel 6a
Build number: TQ2A.230305.008.E1.2023032600
Stock clock app

My auto reboot is set to every 8 hours, and I have the alarm set from a second profile. It has definitely worked fine in the past

**Comment by thestinger** [comment]
It's normal that it won't work from a secondary user after reboot. Only Owner is running in Direct Boot mode after reboot, and doesn't have access to regular profile / system data stored in owner, only Direct Boot data.

**Comment by wellthissucks** [comment]
OK, so it's been a while since I looked at this.

This still doesn't work on my Pixel 4a. I just made sure it was completely up to date, then tested it, and it's still the same. Alarm is silent after a reboot.

I have recently just put Graphene on a brand new 6a, and in the process of setting it up with apps and getting it ready for use. Right now it's a stock GOS install, with no new apps or anything, not even a sim card. It seems to work properly on this 6a as it stands.

**Comment by thestinger** [comment]
Clear clock app data and try again.

**Comment by wellthissucks** [comment]
First, I cleared the app data like you suggested. That seemed to work, so I setup all of my regular alarms again after that, then tested it again, and it would only vibrate after the auto-reboot (4a which is my current phone). I got the shits and tested it on the new 6a again, and it worked fine. Now I'm getting pissed off.

So Ive been sitting here testing this for hours now, here is what I've worked out.

Both the 4a and the 6a act exactly the same way.

At first I thought it was something to do with the non-stock sounds that I've been using for years. They are simple mp3 files dropped into the Alarms folder via a PC. These sounds most certainly worked before I originally posted this issue 7 months ago. But then I had stock sounds do the same thing, the alarm goes off and is showing on the screen, but it only vibrates, with no sound.

So I cleared the app data again and started again on both phones. As it sits after clearing the data, using it as it ships, setting the time only, not touching any other settings or changing the sound, it seems to work fine after a reboot.

Then I changed a few of the master alarm settings in the clock app, _Silence After_ set to never, _Snooze_ time set to 5 minutes, but kept the same stock sounds. It works fine again.

Then I changed the sound to the same non-stock one on both phones. The new sound didn't work, and the alarm was the default sound. Even though these new sounds have been added to the folder via PC (which is all I've ever had to do in the past 10 years or so, and they show up in the list for selecting a sound, they didn't work). But it **DID** work after an auto-reboot.

WTF? This has never happened before.

So, in the list for selecting the alarm sound, there is an _+Add New_ option at the top. I don't recall ever having to use this before, I dodn't even recall ever seeing it before. But in the interests of testing, I used it to select the same non-stock sound on both phones (that is actually already in the list shown below it, in the same folder). It's still working after a reboot, but it's **STILL** playing the defult sound.

WTF?

Clear all app data again. Change just the time, and test both. Both work after auto-reboot.

Change the default alarm sound in the main **Settings > Sounds** menu to one of the non-stock ones. Hey now we're getting somewhere. Both phones worked this time.

Next, I tried setting multiple different alarms all a couple of minutes apart, all using different sounds, just to see how those react. I was thinking that only the first one after a reboot should be affected by this weirdness... Hmmm, nope... The sounds on the subsequent alarms aren't playing the selected sounds either. They're working, they make noise and the phone vibrates, but the sound is some generic sound that I can't even find anywhere.

If I turn off the auto-reboot feature, and had it in a normal state, no reboot... **ALL OF THE ALARMS WORK FINE.** They play the sounds that have been selected, they vibrate, everything works.

There is one more setting that I wanted to test, so I did it with a manual reboot... The one that is _Gradually Increase Volume_ set at 5 seconds. I've always had this set in the past, including before this issue first happened 7 months ago. Hey guess what. This is the one that kills the alarm sound after a reboot. This is the one that causes the condition that I first saw 7 months ago. The alarm is activated on the screen, the phone vibrates, but there is no sound.

So in conclusion, this has pissed me off enough for one day. I've been testing this for hours, and there is no result that allows me to use the auto-reboot feature, **AND** have the alarms work properly.

**So, this issue is NOT RESOLVED.** It used to work perfectly before I originally posted this issue. I could just set any alarm I wanted using any sound I liked, and it would just work, no matter if it rebooted or not. As it stands right now, it still doesn't work after any reboot, auto or manual. The only thing for it is to turn off the auto-reboot again and just live with the fact that one of the advertised features of this OS simply isn't compatible with a regular feature of a mobile phone that millions of people use every day... a fully functioning alarm clock app.

I've got the shits, I'm going to bed.

**Comment by mo-st** [comment]
Hi, I'm having this issue as well on a fully updated 6a with a none stock alarm app. I second the observation that this only happens when certain settings in the alarm app are changed as it worked fine until about a week ago. I can't confirm that it's the "Gradually increase volume" one yet though as I haven't gotten around to testing it yet and I keep this turned off at all times. If I find the time to look into it more closely I'll report again, but it seems to be an upstream issue anyway so I guess not much to do besides increasing the auto reboot time for now.

**Comment by tinfever** [comment]
I just had this happen to me this morning. My phone rebooted due to an update overnight, and for my morning alarm the phone vibrated but did not play any sound like it should. I'm using the stock Clock app.

Alarm Configuration:
Sound: Neon
Vibrate: Yes
Silence After: Never
Snooze Length: 10 minutes
Alarm volume: Looks like 90% of slider position.
Gradually increase volume: 30 seconds

This is quite concerning. It's very important that the alarm always work. I'm going to have to disable auto reboots to make sure this doesn't happen again.

**Comment by thestinger** [comment]
You don't have to disable the auto-reboot feature, only increase the interval to more than your sleep period. If you're referring to the automatic reboot while idle feature for the update client, that makes sense. They're separate features.

**Comment by tinfever** [comment]
Thank you. Yes, I was referring to the "Automatically reboot once the device is idle after successfully installing an update" setting.

**Comment by orionszbelt** [comment]
Why is this issue closed? I can confirm the issues with alarm, no sound after reboot overnight. There are other issues with alarm as well. What is the current open defect?

**Comment by orionszbelt** [comment]
> @orionszbelt There's an issue with the toggle for raising the volume level. Try without it.

I do not even have this option available. It does not exist in my os 2024011600

**Comment by bakeromso** [comment]
I can confirm this is an issue for me still too.

Build number  2024030300
Android 14

**Comment by SamGSquared** [comment]
Not sure why this issue was closed. Still experiencing this on build 2024092900
