### ISSUE TITLE
Biometric prompt missing when switching profiles

### ISSUE THREAD

**Issue by natert** [GrapheneOS/os-issue-tracker#1611]
Biometric prompt is delayed when switching from secondary profile to owner on pixel 7.

**Comment by thestinger** [comment]
We can't track every upstream issue here. No activity on this issue so it doesn't need to be tracked here unless a contributor plans on working on it.

**Comment by Jawshy** [comment]
I'm experiencing a similar issue. 

Expected: Fingerprint unlocks device after unlocking with password and locking

Actual: Can only unlock device with password

Steps to reproduce: 
1. Setup multiple profiles
2. Register fingerprints and enable unlocking with fingerprints on all profiles
3. With device unlocked using password, switch to another profile
4. Unlock with password
5. Lock device
6. Attempt to unlock with fingerprint (may not work)
7. Switch to another profile and unlock with fingerprint (may not work)

Allow fingerprint unlocking is enabled. I’ve rebooted my phone. I’ve noticed this issue before version: TQ3A.230605.010.2023062300. I was told in #grapheneos:grapheneos.org that this is a known upstream issue that has existed for a while and it has became more prevalent since Android 13 QPR3. 
Device: Pixel 6a

**Comment by zachvlat** [comment]
> I'm experiencing a similar issue.
> 
> Expected: Fingerprint unlocks device after unlocking with password and locking
> 
> Actual: Can only unlock device with password
> 
> Steps to reproduce:
> 
> 1. Setup multiple profiles
> 2. Register fingerprints and enable unlocking with fingerprints on all profiles
> 3. With device unlocked using password, switch to another profile
> 4. Unlock with password
> 5. Lock device
> 6. Attempt to unlock with fingerprint (may not work)
> 7. Switch to another profile and unlock with fingerprint (may not work)
> 
> Allow fingerprint unlocking is enabled. I’ve rebooted my phone. I’ve noticed this issue before version: TQ3A.230605.010.2023062300. I was told in #grapheneos:grapheneos.org that this is a known upstream issue that has existed for a while and it has became more prevalent since Android 13 QPR3. Device: Pixel 6a

To add to this, also after multiple of unlocks via pin, eventually you can unlock it with fingerprint. I didn't count how many times I had the pin prompt, though.

**Comment by OfficialMuffin** [comment]
Same issue here on Pixel 6a. Fingerprint prompt does not show on lockscreen after switching profiles.

Build version: TQ3A.230605.010.2023062300

**Comment by Peter-Harmann** [comment]
I just noticed it is more specific. The fingerprint unlock works when I lock the phone a switch from locked screen but does not work when switching from unlocked device.

**Comment by dithmal** [comment]
Found kind of a workaround to this (I think). If I use an app that has biometric unlocking enabled, the fingerprint device unlock also starts working again. Mentioning here thinking it might be relevant/helpful to the devs and users.

Device: Pixel 6
Version: TQ3A.230605.010.2023062800

Cheers!

**Comment by WofWca** [comment]
Forum posts about this:
* https://discuss.grapheneos.org/d/5516-fingerprint-while-switching-profiles
* https://discuss.grapheneos.org/d/5616-grapheneos-version-2023061402-released
* https://discuss.grapheneos.org/d/5691-biometrics-not-available-after-switching-back-to-owner-profile
* https://discuss.grapheneos.org/d/5731-bug-fingerprint-unlock-disabled-after-profile-change

**Comment by zachvlat** [comment]
I can confirm with the recent update, it works on my Pixel 7 Pro.

**Comment by Peter-Harmann** [comment]
I am still having the issue with build TQ3A.230805.001.2023090600 on Pixel 7 Pro

**Comment by zachvlat** [comment]
> I am still having the issue with build TQ3A.230805.001.2023090600 on Pixel 7 Pro
> 
> @zachvlat are you perhaps on a beta/alpha channel?

no Stable

**Comment by zachvlat** [comment]
> I can confirm with the recent update, it works on my Pixel 7 Pro.

I retract my previous statement. The issue persist.

**Comment by somehuman60** [comment]
> > I can confirm with the recent update, it works on my Pixel 7 Pro.
> 
> I retract my previous statement. The issue persist.

For me, it started with Android 14. I never had such a problem before with Android 13. When I switch from Second Profile to Main Profile, or exit Second Profile, fingerprint sensor shows up very briefly and is replaced with Lock, so I have to enter PIN each time.

**Comment by doma9on** [comment]
Genuinely stumped how little response this issue has had on Google's bug tracker.. Still seeing this issue on 14 (UQ1A.240105.004) and hate having to input my PIN in public when I need to access my phone.. I've tried giving it a few mins before unlocking but bio prompt just never shows lol :)

**Comment by W1zardK1ng** [comment]
After updating to Android 14 QPR2 (GrapheneOS version 2024030800) this issues is resolved for me on my Pixel 6a.

**Comment by somehuman60** [comment]
For me is resolved on Pixel 7 Pro.

**Comment by dithmal** [comment]
Not resolved (Pixel 6, build number 2024030800).

**Comment by GCLW1994** [comment]
Not resolved for me either. Really annoying :/ 

It randomly and infrequently pops up sometimes. Most of the time it just constantly switches between the locked icon and the fingerprint icon. 

Pixel 6, Build 2024031100

**Comment by GCLW1994** [comment]
> > Not resolved for me either. Really annoying :/
> > It randomly and infrequently pops up sometimes. Most of the time it just constantly switches between the locked icon and the fingerprint icon.
> > Pixel 6, Build 2024031100
> 
> Could you try gettin logs from Settings > System > View logs right after reproducing this to see if we can get anything relevant from there?

Here you go! Hope there's nothing private, and it'll be useful (hopefully I did it right) :)

Let me know if I can help with anything else.

[System log 273c6f4a8f65.txt](https://github.com/GrapheneOS/os-issue-tracker/files/14609214/System.log.273c6f4a8f65.txt)

**Comment by GCLW1994** [comment]
> > Not resolved for me either. Really annoying :/
> > 
> > It randomly and infrequently pops up sometimes. Most of the time it just constantly switches between the locked icon and the fingerprint icon.
> > 
> > Pixel 6, Build 2024031100
> 
> Could you try gettin logs from Settings > System > View logs right after reproducing this to see if we can get anything relevant from there?

Hey there. Seems to be a resolution in the forums: 
https://discuss.grapheneos.org/d/5731-bug-fingerprint-unlock-disabled-after-profile-change 

Hope it works!

**Comment by FID02** [comment]
`I` can repro on stock with these steps: add 4 fingerprints in Owner, create a new *guest* user and switch to it, then add a fingerprint in the guest user, then exit the guest session. The owner profile lock screen then glitches out, shows the fingerprint unlock option for about 0.3 seconds a couple of times. Can only unlock with PIN.

Did these steps twice to confirm, with a reboot in between before reproing the second time.

**Comment by hollunder** [comment]
Same problem with Pixel 6a.
The mentioned workaround does not seem to work for me.
Maybe I misunderstood it, maybe someone here can rephrase/summarize how it is supposed to work?

**Comment by GCLW1994** [comment]
> Same problem with Pixel 6a.
> The mentioned workaround does not seem to work for me.
> Maybe I misunderstood it, maybe someone here can rephrase/summarize how it is supposed to work?

Hopefully I'm explaining this right. 

Have two fingerprints registered in owner profile, two fingerprints in second profile. Can't have more than two, and also need to have the same number. 

Currently, there's a new bug where the pinpad shows up when switching profiles. Workaround is to just go back i.e. swipe or button, and the fingerprint reader will come up. 

Hope that clears things up and it works :)

**Comment by hollunder** [comment]
> > Same problem with Pixel 6a.
> > The mentioned workaround does not seem to work for me.
> > Maybe I misunderstood it, maybe someone here can rephrase/summarize how it is supposed to work?
> 
> Hopefully I'm explaining this right.
> 
> Have two fingerprints registered in owner profile, two fingerprints in second profile. Can't have more than two, and also need to have the same number.
> 
> Currently, there's a new bug where the pinpad shows up when switching profiles. Workaround is to just go back i.e. swipe or button, and the fingerprint reader will come up.
> 
> Hope that clears things up and it works :)

Thank you for your explanation!

I currently have three profiles. I tried it today with two fingerprints in each and also with one fingerprint in each, but neither worked. I guess it is time to delete one of the profiles and try again.

Regarding the back swipe or button, at least the swipe does not seem to work for me on the lock screen.

**Comment by hollunder** [comment]
OK, I could not get it to work with three profiles, but with two and one fingerprint each as well as with two and two fingerprints each it seems to work. Thank you!

I now also see what you mean with the other bug. I get the pin pad overlaid on the lock screen with the fingerprint sensor icon. I then need to swipe up to be able to use the fingerprint sensor.

**Comment by GCLW1994** [comment]
> OK, I could not get it to work with three profiles, but with two and one fingerprint each as well as with two and two fingerprints each it seems to work. Thank you!
> 
> I now also see what you mean with the other bug. I get the pin pad overlaid on the lock screen with the fingerprint sensor icon. I then need to swipe up to be able to use the fingerprint sensor.

Glad it partially fixed! Fingers crossed next AOSP update fixes all of these.

**Comment by hollunder** [comment]
> Glad it partially fixed! Fingers crossed next AOSP update fixes all of these.

I hope so too.
Bugs like these make me wonder which other bugs lurk around login and user switching.
It is not exactly inspiring confidence in Android in general and GrapheneOS in particular.

**Comment by Peter-Harmann** [comment]
Unfortunately, this bug now also blocks login with 2-factor (fingerprint + pin). After ending a session in different profile now always require primary authentication, which would ideally be diceware password.

Therefore, this bug now blocks me and anyone else who routinely uses profiles from adopting diceware password primary unlock with 2FA secondary, which seems to be the recommended setup.

**Comment by tired-creating-those-usernames** [comment]
Two years and still open...
Devs use iPhones I presume?...

**Comment by WaleedMortaja** [comment]
I have enabled `Allow running in background` toggle for a profile that I have added a (one) fingerprint to it, and I cannot reproduce the issue.

Switching to any profile seems to automatically try to unlock the profile in about half a second after switching (If there is no lock, the main launcher automatically appears. If there is a PIN, it prompts for that PIN). However if there is a fingerprint, it seems to glitch: The sensor icon changes from fingerprint to lock then back to fingerprint, the background becomes darker, only the fingerprint sensor is highlighted (not darker); but this does not affect the functional of the sensor I do not think it took more than half a second to be prepared to unlock with fingerprint. The glitch seems to be an issue, but I does not bother me enough to report it myself at the time.

If I disable `Allow running in background` toggle for the profile, then switch from it is the same as ending the session, for which case a PIN was required with a message of `PIN is required after device restart` which I think is a clear indication that ending a profile session or switching from a profile that has `Allow running in background` being disabled has the same effect as restarting the whole device for that profile.

I have Pixel 6a, latest update as of today.

**Comment by zachvlat** [comment]
My experience so far is completely random. I found my self switching to the 2nd profile and the bio-metrics work as intended, and sometimes not. On top of that, when I switch back to my main profile (the 1st one) 90% asks me for a pin. There are some cases that it doesn't asks me and all work flawlessly.

**Comment by shalzz** [comment]
> I have enabled `Allow running in background` toggle for a profile that I have added a (one) fingerprint to it, and I cannot reproduce the issue.
> 
> Switching to any profile seems to automatically try to unlock the profile in about half a second after switching (If there is no lock, the main launcher automatically appears. If there is a PIN, it prompts for that PIN). However if there is a fingerprint, it seems to glitch: The sensor icon changes from fingerprint to lock then back to fingerprint, the background becomes darker, only the fingerprint sensor is highlighted (not darker); but this does not affect the functional of the sensor I do not think it took more than half a second to be prepared to unlock with fingerprint. The glitch seems to be an issue, but I does not bother me enough to report it myself at the time.
> 
> If I disable `Allow running in background` toggle for the profile, then switch from it is the same as ending the session, for which case a PIN was required with a message of `PIN is required after device restart` which I think is a clear indication that ending a profile session or switching from a profile that has `Allow running in background` being disabled has the same effect as restarting the whole device for that profile.
> 
> I have Pixel 6a, latest update as of today.

I agree, this works for me as well and I don't consider this bug to be open anymore or at least the original bug that this issue was opened for has indeed been fixed.
