### ISSUE TITLE
Fingerprint Scan fails

### ISSUE THREAD

**Issue by Redback813** [GrapheneOS/os-issue-tracker#1773]
G'day All
I may have just discovered a bug with the fingerprint scanner, went I installed Grapheneos sometime ago I gave it two fingerprints to register. But today, I discovered that any fingerprint will unlock the Google Pixel 7 mobile from a lock screen. Even when the user restarts the mobile phone the pattern can be repeated, however, you can't bypass the keypad.

To test this, make sure the screen is locked, then tap screen to activate then use any finger that not associated with the fingerprint scanners and tap firmly on scanner, see if the screen unlocks, or perhaps it just me.

Thanks in advance

**Comment by thestinger** [comment]
The fingerprint scanner on 6th and 7th generation issues is known to have upstream issues which were resolved in more recent releases and require re-registering fingerprints.

**Comment by Redback813** [comment]
Thanks for the feedback, I was not aware of the issue, anyway did a re-registering fingerprints same problem still.

**Comment by thestinger** [comment]
You need to delete them from all profiles. I suggest a factory reset if that's not working for you.

**Comment by Redback813** [comment]
Sorry to say, but a factory reset doesn't resolve the issue either, as the scanner says fingerprint not recognised, and still open to the keypad.

**Comment by thestinger** [comment]
I need you to clarify what you're reporting. I don't think I understand your original report.

**Comment by Redback813** [comment]
When I first install GrapheneOS on the Google Pixel 7, I went through the normal procedure of setting up a profile as well as doing the fingerprint, screen lock pin, network etc and all went well. Today, I discover by accident that I can unlock a “locked screen” with any fingerprint that is not registered to the device.
  So I deleted the two fingerprint that were registered and created one new registered fingerprint, just like “thestinger” suggested, then I tried the same error pattern: test run.
  Make sure the screen is locked, then activate the screen, use any finger that not registered with the device and place firmly on the scanner, and see if the screen unlocks.
     And still the device failed to stop any unregistered fingerprint from unlocking the screen, so I did a factory reset like “thestinger” recommend and that failed as well, with stopping any unregistered fingerprint from unlocking the screen. The error, msg each time, was “fingerprint not recognised” and yet it still unlocked the screen when applying any unregistered fingerprints.
	 
Thanks in advance.

**Comment by thestinger** [comment]
We think this a hardware flaw. Since you've already done a factory reset, I recommend trying the stock OS.

**Comment by Redback813** [comment]
Nope, after going through all that trouble, I will disable the fingerprint instead on the pixel 7 for lock screen, hence it still save with the pin screen and a disabled USB. Try another mobile phone “Huawei Mate9” with fingerprint scanner, and it's suffering from the same hardware failure as Pixel 7, press several times on the scanner with any finger not registered, and it will show the screen pin as well. Try your own mobile and see if the trick work. Hmm, hardware indeed.

**Comment by thestinger** [comment]
I still don't really understand exactly what you're reporting since now you're talking about it not registering.
