### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by W1zardK1ng** [GrapheneOS/os-issue-tracker#2042]
After the latest update, microphone is not working after phone is in idle for some time.
Even after picking the calls the green dot is not showing up.
Disabing and enabling Mic access from quick settings fixes the issue.

device : Pixel 6a (T2B3.230109.009.2023031500)

**Comment by alizair** [comment]
I would second this, there is definitely something funky going on with the microphone.

**Comment by alizair** [comment]
> Do you have the global camera toggle on or off? Try turning that on and see if the mic works.

I did have it off most of the time, but whenever I used to turn it on, it worked perfectly. However, after this update, I sometimes had to turn it off and back on, to make it work. Also, I noticed that the button also seems to not be responding the way it used to before. When I used to click it, it turned on and vice versa, but now it sometimes doesn't even turn off after I click it once.

> I think you're stumbling across a new AOSP bug introduced by QPR2.

Possible but I am not sure.

**Comment by VRT-secure** [comment]
Hello comrades, on pixel 4a the similar problem

**Comment by lprell** [comment]
Same thing on Pixel 7. Global camera toggle on off. Will enable global camera access on for a few days and test it out.

**Comment by thestinger** [comment]
Appears fixed by latest AOSP release.

**Comment by ElonSatoshi** [comment]
I still have an issue where my microphone doesn't work in speaker mode

Microphone works fine if I'm not in speaker mode, calling someone, and my 4a is up to my ear.

**Comment by thestinger** [comment]
That's a hardware issue. It's a different microphone and one of them in your device is dead.

**Comment by thestinger** [comment]
Not relevant to this issue, which was not the same thing as that and was resolved.
