### ISSUE TITLE
Calling Accounts reverting

### ISSUE THREAD

**Issue by githubdotcomaccount** [GrapheneOS/os-issue-tracker#2204]
Calling Accounts in the Dialer are not sticking after a reboot. The setting reverts to default SIM. 

I'm running GrapheneOS on a 5a but from what I have been hearing, the issue is not unique to my model. 

This issue was reported a couple of years ago and looks like it was resolved, but seemingly came back. 
https://github.com/GrapheneOS/os-issue-tracker/issues/622

From what I'm told, this should be the patch needed:
https://android-review.googlesource.com/c/platform/frameworks/opt/telephony/+/2022115

**Comment by aboveagency** [comment]
+1 for this. Useful VoIP phone apps like Cheogram (which connects to the jmp.chat service) integrate with the system dialer. Setting up a permanent calling account makes it so you make calls over the internet and avoid using the SIM card. This adds privacy as calls using VoIP bridge out to the cellular network from one origin, instead of the tower closest to you. 

Because of a bug in AOSP, these calling accounts get reset with every reboot. This can cause a user to make a call using the default calling account / sim card, which could ruin an attempt at keeping separate calling identities using GrapheneOS. 

I know myself and the XMPP / Cheogram / JMP chat community would be very grateful if this bug could be fixed. I would say there are more than a hundred users that are using GrapheneOS + Cheogram / JMP. This would be an important fix! 

Thank you.

**Comment by avatar382** [comment]
I'm also an XMPP/Cheogram user and I'm having this issue as well.

**Comment by TriggerDingus** [comment]
+1  This has been a pain since I started using Cheogram on my Android last year. After every reboot, I often forget I have to re-fix this setting because of 'the bug'.

**Comment by virtuousvector** [comment]
+1

I'd be curious what others are doing to work around this ... removing Cheogram from caller accounts and just using the clumsy Cheogram interface? Unfortunately "ask me first" won't persist either.

**Comment by singpolyma** [comment]
Reports from most users have been that this is resolved as of Android 14

**Comment by thestinger** [comment]
GrapheneOS has had Android 14 in the stable channel since October 10th and is based on Android 14 QPR1 now. Are people still having the issue? It's possible they fixed it in an APEX mainline update. APEX mainline releases have more changes than what's included in AOSP monthly/quarterly releases, unfortunately. We aren't currently building and shipping the APEX mainline updates since it would be quite a complex mess (Google Play system updates is the branding for their builds).

**Comment by thestinger** [comment]
We probably will start shipping the APEX mainline updates but we have no timeline for it. It's going to be a real pain to deal with dozens of modules, each with their own AOSP tags, where we need to have our changes applied for building them. They also aren't designed to be built into the OS so you have to ship them out-of-band. The initial OS boot has the AOSP OS variant of the APEXes rather than the mainline ones, and the same thing applies after factory reset. It would be so much cleaner if they included all the changes in monthly updates, or at least quarterly ones.

**Comment by virtuousvector** [comment]
@singpolyma @thestinger Whoa. I just tested this again this morning and it does indeed seem to be working as desired. I believe it was not working as recently as a few days ago. Perhaps a recent GOS change fixed it? This is huge! (Once issue #2871 is resolved on the Cheogram side).

**Comment by dm17** [comment]
Definitely not fixed

**Comment by dm17** [comment]
> @singpolyma @thestinger Whoa. I just tested this again this morning and it does indeed seem to be working as desired. I believe it was not working as recently as a few days ago. Perhaps a recent GOS change fixed it? This is huge! (Once issue #2871 is resolved on the Cheogram side).

How did you test? 1) Android phone app -> set "ask every time" -> it works 2) reboot phone 3) see that it is set to SIM rather than "ask every time"

**Comment by thestinger** [comment]
@dm17 That's different than setting it to something specific. Does it remember if you set it to another option?

**Comment by dm17** [comment]
> @dm17 That's different than setting it to something specific. Does it remember if you set it to another option?

I haven't tried that but I will some time - I just have no use for one or the other; just both ("ask every time").
Thanks.

**Comment by dm17** [comment]
I just tried with the specific non-SIM calling account as well. For me both "ask every time" and selecting the specific calling account: both reset on reboot. The SIM account is always selected after a reboot.

**Comment by dm17** [comment]
I've never not had to go in and re-select it in the ~4 years of using GrapheneOS.

**Comment by virtuousvector** [comment]
I only have two calling accounts right now, one physical SIM and one Cheogram account. (Wondering out loud if the quantity and type of calling accounts plays a role. I know that would be weird.)

Here is what I just did:

1. Change calling account from "ask" to cheogram.
2. Restart
3. Calling account has reverted to SIM.
4. Change calling account from SIM to "ask."
5. Restart
6. Calling account has reverted to SIM.
7. Change calling account to Cheogram.
8. Restart
9. Calling account has persisted on Cheogram.

(And I also did this a few more times but saw the same pattern). 

Here's a weird thought ... Something DEFINITELY changed for me recently. And the other relevant thing I changed recently was disabling my original SIM card, experimenting with a new ESIM, then disabling the ESIM and re-enabling the original SIM. But my Cheogram account -- established AFTER the original SIM -- stayed on the whole time. Is it possible that the only time it will persist on a non-SIM calling account is when there is a non-SIM account that has been continuously connected for longer? Let's call it tenure? Will it only persist a non-SIM option if that option has a longer tenure than any active SIMs?

**Comment by githubdotcomaccount** [comment]
Confirming it still reverts for me as well, regardless of whether I default any of my calling accounts or set it to Ask First. The only time it did not revert for me is when I had two SIM (physical and eSIM) simultaneously, then it stuck on Ask First. I assume maybe the privileged eSIM was able to override it or something but I honestly have no idea.

**Comment by githubdotcomaccount** [comment]
I still am having this issue. Is there any possibility of adding in this patch?

https://android-review.googlesource.com/c/platform/frameworks/opt/telephony/+/2022115

**Comment by BurnyBoi** [comment]
For me "Make Calls With" consistently reverts back to the SIM when I toggle my SIM with "Turn off" then "Turn On"  under Network & Internet, SIMs. This happens regardless if "Make Calls With" is set to my Cheogram account or "Ask First"

**Comment by githubdotcomaccount** [comment]
This seems to have been fixed in a recent update. "Ask First" has stuck over the last several reboots for me.

**Comment by githubdotcomaccount** [comment]
This behavior started happening again for me somewhat recently. Unfortunately I do not know precisely when, but it was at least several releases ago. Maybe a month or so?

**Comment by TriggerDingus** [comment]
> This behavior started happening again for me somewhat recently. Unfortunately I do not know precisely when, but it was at least several releases ago. Maybe a month or so?

It was never actually fixed for me. It doesn't seem the CalyxOS team can fix it and the upstream team(s) apparently don't have the issue or perceive it to be one. It would be a small, yet monumental, issue to be resolved for me if it ever does get resolved.
