### ISSUE TITLE
GrContext is abandoned/device lost at start of CanvasContext::draw

### ISSUE THREAD

**Issue by mattinahat13** [GrapheneOS/os-issue-tracker#2700]
I am running into an issue where my phone will freeze and require a reboot by holding the power button for 20 seconds. It mostly happens while I am on a walk where I will be playing music/podcasts over Bluetooth/wired headset and have the flashlight on, but it has happened randomly as well. I will note the phone is more stable while connected to wifi. Any app that is open will crash and include this in the error message: Abort message: 'GrContext is abandoned/device lost at start of CanvasContext::draw'.

I have experienced the crash with these apps:  Signal, AntennaPod Simple Music Player, Clock, Cheogram, Settings, Launcher, and SystemUI. The crash will often turn off my flashlight, but not the music playing.

I will note that I do not have GPlay services/store installed, but I did use them at one point to download an eSIM.
I do have a secondary profile installed.

This issue doesn't occur on my Pixel 7 Pro, but does on my Pixel 8.

```
type: crash
osVersion: google/shiba/shiba:14/UD1A.230803.041/2023102300:user/release-keys
package: com.android.settings.intelligence:34
process: com.android.settings.intelligence
processUptime: 0 + 0 ms

signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'GrContext is abandoned/device lost at start of CanvasContext::draw'

backtrace:
      #00 pc 000000000006eca4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 70e39a6810cd2a8f7b6f23f9b5ea610d)
      #01 pc 000000000064be80  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456) (BuildId: 6ea39c7629f248392ceeb7f63efc9f64)
      #02 pc 0000000000044730  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: fe892b2afe1b21a706992b20886336f8)
      #03 pc 0000000000011fd4  /system/lib64/liblog.so (__android_log_assert+308) (BuildId: 7b2c8efcf19100c35d7cd5b687e6277a)
      #04 pc 0000000000292c04  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2580) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #05 pc 000000000029516c  /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #06 pc 00000000002840c0  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #07 pc 00000000002a66b4  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #08 pc 000000000001530c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284) (BuildId: 6536c636a18676bd5113fb0378052e1c)
      #09 pc 00000000000db93c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 70e39a6810cd2a8f7b6f23f9b5ea610d)
      #10 pc 0000000000070570  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 70e39a6810cd2a8f7b6f23f9b5ea610d)


```

**Comment by mattinahat13** [comment]
```
type: crash
osVersion: google/shiba/shiba:14/UD1A.231105.004/2023111500:user/release-keys
package: org.thoughtcrime.securesms:136105
process: org.thoughtcrime.securesms
processUptime: 0 + 0 ms
installer: com.android.packageinstaller

signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'GrContext is abandoned/device lost at start of CanvasContext::draw'

backtrace:
      #00 pc 000000000006e324  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: ec367bcc42a0769197eb58413b7349bd)
      #01 pc 000000000064be80  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456) (BuildId: f7bdda9948b15b446da6cfac2db76877)
      #02 pc 0000000000025890  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: fc5b70c8411b7c6faefe49f9d8fea01e)
      #03 pc 0000000000011fd4  /system/lib64/liblog.so (__android_log_assert+308) (BuildId: 7b2c8efcf19100c35d7cd5b687e6277a)
      #04 pc 0000000000292c04  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2580) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #05 pc 000000000029516c  /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #06 pc 00000000002840c0  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #07 pc 00000000002a66b4  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404) (BuildId: 56a6ea38174b012e1e73074e7c0a4b2e)
      #08 pc 000000000001530c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284) (BuildId: 6536c636a18676bd5113fb0378052e1c)
      #09 pc 00000000000daeac  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: ec367bcc42a0769197eb58413b7349bd)
      #10 pc 000000000006fbf0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ec367bcc42a0769197eb58413b7349bd)


```

**Comment by mattinahat13** [comment]
Hello, I recently got 2 new crash dialogues since the update:

```
type: crash
osVersion: google/shiba/shiba:14/UD1A.231105.004/2023112600:user/release-keys
uid: 10109 (u:r:systemui_app:s0:c109,c256,c512,c768)
cmdline: com.android.systemui
processUptime: 4100s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread
MTE: enabled

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 6e464)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 25890)
    /system/lib64/liblog.so (__android_log_assert+308, pc 11fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2580, pc 292c04)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324, pc 29516c)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840c0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a66b4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1530c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc db00c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 6fd30)
```

```
type: ANR
osVersion: google/shiba/shiba:14/UD1A.231105.004/2023112600:user/release-keys
package: android:34
process: system

activity: null
cause: ANR Input dispatching timed out (PointerEventDispatcher0 (server) is not responding. Waited 5003ms for MotionEvent)
info: ANR in system
PID: 1313
Reason: Input dispatching timed out (PointerEventDispatcher0 (server) is not responding. Waited 5003ms for MotionEvent)
ErrorId: e021e5d3-2713-4ccc-9ae1-ae2f3531cd21
Frozen: false
Load: 3.22 / 2.43 / 2.62
----- Output from /proc/pressure/memory -----
some avg10=0.04 avg60=0.02 avg300=0.03 total=10712689
full avg10=0.04 avg60=0.02 avg300=0.00 total=8178618
----- End output from /proc/pressure/memory -----
----- Output from /proc/pressure/cpu -----
some avg10=6.19 avg60=4.50 avg300=4.25 total=382599500
full avg10=0.00 avg60=0.00 avg300=0.00 total=0
----- End output from /proc/pressure/cpu -----
----- Output from /proc/pressure/io -----
some avg10=0.00 avg60=0.00 avg300=0.00 total=8605581
full avg10=0.00 avg60=0.00 avg300=0.00 total=5816526
----- End output from /proc/pressure/io -----

CPU usage from 12573ms to 93ms ago (2023-11-27 15:56:23.505 to 2023-11-27 15:56:35.986):
  25% 1313/system_server: 13% user + 12% kernel / faults: 50207 minor 33 major
  21% 624/surfaceflinger: 12% user + 9.2% kernel / faults: 7144 minor 215 major
  6.6% 18158/org.thoughtcrime.securesms: 5.8% user + 0.8% kernel / faults: 1936 minor 6 major
  4.5% 631/android.hardware.composer.hwc3-service.pixel: 2% user + 2.4% kernel / faults: 2 minor
  3.7% 1733/kworker/u18:11-events_unbound: 0% user + 3.7% kernel
  2.9% 1968/com.android.systemui: 2% user + 0.9% kernel / faults: 2044 minor 1 major
  2.2% 569/sugov:4: 0% user + 2.2% kernel
  2% 936/android.hardware.sensors-service.multihal: 0.8% user + 1.1% kernel
  1.6% 1136/media.swcodec: 0.4% user + 1.2% kernel / faults: 4845 minor
  1.2% 383/decon0_kthread: 0% user + 1.2% kernel
13% TOTAL: 5.6% user + 6.3% kernel + 0.1% iowait + 0.7% irq + 0.3% softirq
CPU usage from 13ms to 401ms later (2023-11-27 15:56:36.092 to 2023-11-27 15:56:36.479):
  96% 103/kswapd0: 0% user + 96% kernel
  54% 1313/system_server: 27% user + 27% kernel / faults: 902 minor
    27% 8031/AnrAuxiliaryTas: 10% user + 17% kernel
    10% 4604/RenderThread: 6.8% user + 3.4% kernel
    3.4% 1350/binder:1313_2: 0% user + 3.4% kernel
    3.4% 1542/android.anim: 3.4% user + 0% kernel
    3.4% 1595/PowerManagerSer: 0% user + 3.4% kernel
    3.4% 1791/SensorService: 0% user + 3.4% kernel
  17% 624/surfaceflinger: 11% user + 5.9% kernel / faults: 71 minor
    8.9% 624/surfaceflinger: 5.9% user + 2.9% kernel
    5.9% 746/app: 2.9% user + 2.9% kernel
    2.9% 673/RenderEngine: 2.9% user + 0% kernel
    2.9% 744/TouchTimer: 2.9% user + 0% kernel
    2.9% 747/appSf: 0% user + 2.9% kernel
    2.9% 760/surfaceflinger: 2.9% user + 0% kernel
    2.9% 2597/binder:624_5: 2.9% user + 0% kernel
  6% 631/android.hardware.composer.hwc3-service.pixel: 0% user + 6% kernel
    3% 631/binder:631_3: 0% user + 3% kernel
  2.6% 14/rcu_preempt: 0% user + 2.6% kernel
  2.6% 59/rcuop/5: 0% user + 2.6% kernel
  2.8% 383/decon0_kthread: 0% user + 2.8% kernel
  2.8% 405/csf_scheduler: 0% user + 2.8% kernel
  2.9% 554/lmkd: 0% user + 2.9% kernel
    2.9% 554/lmkd: 0% user + 2.9% kernel
  3.7% 3453/com.android.providers.media.module: 3.7% user + 0% kernel
30% TOTAL: 7.9% user + 21% kernel + 0.8% irq + 0.2% softirq

```

**Comment by nobunagaPirate** [comment]
Im experiencing the same error logs, but no freezeing, just crashes. I posted about it here:

https://discuss.grapheneos.org/d/9030-apps-crash-on-pixel-8-pro

Are there any temporary workarounds? My phone is unusable at times.

**Comment by thestinger** [comment]
It will likely be fixed by today's release.

**Comment by mattinahat13** [comment]
Hi @thestinger, the issue still occurs for me. I was able to find a method to spoof it earlier:

- left the house
- phone disconnected from wifi (wifi turned off after 30 sec)
- opened signal, clicked a chat
- clicked on the message line so openboard came up
- swiped through the chat for a few seconds with the on-screen keyboard open and then it crashed

I will note that I am unable to replicate this spoof on wifi

```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.231205.015/2023121200:user/release-keys
package: ch.protonmail.android:939
process: ch.protonmail.android
processUptime: 0 + 0 ms
installer: com.aurora.store

signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'GrContext is abandoned/device lost at start of CanvasContext::draw'

backtrace:
      #00 pc 0000000000063464  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 277ba8901534e0f1dd0e11c86b997fac)
      #01 pc 000000000064be80  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456) (BuildId: 060b039ed21c3da705b85e1c8eb4e543)
      #02 pc 0000000000019890  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: 9e2c9ceec2aca078341a0f73834d2409)
      #03 pc 0000000000006fd4  /system/lib64/liblog.so (__android_log_assert+308) (BuildId: ea2cc209509d537d48836513f498b4c1)
      #04 pc 0000000000292d48  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664) (BuildId: 2ffe8baf3aeabc85707682ba8b37db7e)
      #05 pc 00000000002952ac  /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324) (BuildId: 2ffe8baf3aeabc85707682ba8b37db7e)
      #06 pc 00000000002840d0  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624) (BuildId: 2ffe8baf3aeabc85707682ba8b37db7e)
      #07 pc 00000000002a67f4  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404) (BuildId: 2ffe8baf3aeabc85707682ba8b37db7e)
      #08 pc 000000000001430c  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284) (BuildId: 8371c3b1bd7778d8ad524c2f5adb64da)
      #09 pc 00000000000cffec  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 277ba8901534e0f1dd0e11c86b997fac)
      #10 pc 0000000000064d30  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 277ba8901534e0f1dd0e11c86b997fac)


```

**Comment by thestinger** [comment]
@mattinahat13 Please try again with the latest release.

**Comment by thestinger** [comment]
Ah, that is the latest.

**Comment by TechyPirate** [comment]
I just saw this same thing happen on my Pixel 6a while having YouTube run in the background and using the Reddit app.

````
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 105247s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664, pc 292d48)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324, pc 2952ac)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840d0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a67f4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
````

**Comment by hivefi** [comment]
Maybe this pertains to the same issue. 

```
type: crash
osVersion: [google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys](http://google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys)
uid: 10106 (u:r:platform_app:s0:c512,c768)
cmdline: com.android.systemui
processUptime: 838078s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664, pc 292d48)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324, pc 2952ac)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840d0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a67f4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

**Comment by jmcelroy01** [comment]
When viewing open tabs in Firefox Nightly and closing some of them, this crash occured, requiring a device reboot to eliminate the graphical glitching (Pixel 7 Pro). 

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.231205.015/2023123100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 175780s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62ea4)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664, pc 292d48)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324, pc 2952ac)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840d0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a67f4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

**Comment by mattinahat13** [comment]
@thestinger i haven't received this error since the Feb update. Can't speak for others but it looks like this issue is closed for me

**Comment by nobunagaPirate** [comment]
This issue was resolved for me as well!! Thank you thank you. I love my phone and GOS again
