### ISSUE TITLE
Location stops working with Sandboxed Play Services installed

### ISSUE THREAD

**Issue by eggplanting** [GrapheneOS/os-issue-tracker#635]
**My situation and what I've done:**
- Running the stable build RQ3A.210805.001.A1.2021081822 on my Pixel 4a
- Successfully installed Sandboxed Play Services like mentioned in this guide: https://grapheneos.org/usage#sandboxed-play-services
- Enabled location permission for Google Play Services
- Checked that location is enabled correctly for each app which is requesting the permissions
- Tried multiple apps which need location services to navigate (Magic Earth, Osmand, Google Maps)

**Issue:**
My location only seems to be recognized correctly after a device reboot by several apps.
When the device is up for around 3-4 minutes, the location stops to be working until the next reboot of my device.

**Different behavior by different apps:**
- Magic Earth: After reboot working immediately, after closing the app and waiting 3-4 minutes location is still shown but stuck
- Osmand: After reboot working immediately, after closing the app and waiting 3-4 minutes no location is found until reboot
- Google Maps: After reboot working immediately, after closing the app and waiting 3-4 minutes no location is found until reboot

When location permission for Google Play Services is removed, none of these apps find my location. Not even after a reboot.

This issue seems only to occur when Sandboxed Play Services are installed.

**Comment by eggplanting** [comment]
Just installed GrapheneOS from fresh without Sandboxed Play Services, all apps seem to work without any issues now, no restart needed.

Google Maps recommended to install Play Services on the first start, but it seems to work well apart from that. I will try with a fresh installaton of Play Services to see when the issue is happening.

**Comment by thestinger** [comment]
We're aware that more shims are required for the Play services geolocation APIs to be fully working. An improvement has been made for the next release but more are needed.

**Comment by eggplanting** [comment]
I'm sadly no developer, but would it be possible to add an option which whitelists the use of Sandboxed Play Services for specific apps only?

This would allow to use the location services by GrapheneOS with all apps which are not explicitely whitelisted for Play Services.

Most apps seem to switch to location services provided by Play Services sadly, as soon they are installed.

**Comment by thestinger** [comment]
> I'm sadly no developer, but would it be possible to add an option which whitelists the use of Sandboxed Play Services for specific apps only?

No, because there's nothing special about how this works with Play services and as a rule we aren't providing special integration in the OS. It has no special access or privileges on GrapheneOS. It's simply a regular sandboxed app with the same rules as any other apps.

The OS offers a standard way to choose which apps can communicate with mutual consent: profiles. You can make a dedicated user / work profile for apps with a hard dependency on Play services and only install it there.

> lead to more privacy in general.

Having Play services installed doesn't give apps the ability to use Google services they couldn't use without it. Many of the Google libraries do offer some or most of their functionality without needing Play services, including the Ads SDK which fully works without it other than a few minor things. Play services is simply a regular sandboxed app and we won't be providing any special integration or toggles for it. It wouldn't make any sense and those toggles would be theater that didn't actually work meaningfully. As a rule, we don't make those kinds of features.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/156 is a planned feature as an alternative to profiles but it would have a lot of caveats. Profiles are isolated workspaces with their own instances of apps, app data and shared data without shared data or communication across profiles.

If you disallowed app A and app B from communicating but gave them access to the same shared data like contacts, they could just communicate through contacts. Similarly, if you allowed app A to talk to app C, and allowed app A to talk to app B, then app A and app B could potentially communicate via app C if it intentionally or unintentionally provided a way to do that.

**Comment by eggplanting** [comment]
Thank for your reply, I understand your points from a developers point of view, absolutelty the right decisions.

I further tested how I could accomplish an ideal setup which isolates specific apps from Play Services. Multiple users were no choice, since the environments are isolated completely and apps cannot be shared during runtime. I did set up a work profile with Shelter and installed the Sandboxed Play Services only to the work profile.

And what should I say, it works. Google Maps is finding my location every time without requesting Play Services location permission.

The only issue I see: Google Maps and Youtube for example recognize, that Play Services are installed on the system. When these apps are started from my private profile without Play Services, they open a popup notification each time which tells "Play Services are updated right now". I can click somewhere on the screen and it disappears, which allows me to use Google Maps. That's my solution for now.

Like mentioned the Work profile doesn't seem to be isolated completely, that's why the apps seem to recognize Play Services. Shouldn't they be invisible for my private profile, since they are installed sandboxed as a normal user app, only to my work profile?

**Comment by thestinger** [comment]
This is fixed.

**Comment by thestinger** [comment]
Next release will be in Beta much later today and then probably in Stable within a day or two.

**Comment by pshirshov** [comment]
Actually I'm experiencing exactly the same issues on last release.
All the apps can't get location once I install sandboxed play services using the official guide.
 Is it expected?

**Comment by Zanthed** [comment]
@pshirshov 
> All the apps can't get location once I install sandboxed play services using the official guide.
> They all do work when GPlay services are not installed though.

As stated further above, more work is necessary and still on-going to make Play Services location APIs work properly and consistently.

If Play Services is not installed, the apps will use the OS location APIs to gather location data. If Play Services is installed, it will use Play Services location APIs.

**Comment by thestinger** [comment]
> All the apps can't get location once I install sandboxed play services using the official guide.

Many apps will switch to using Play services location APIs when they're available instead of using the OS APIs. It's entirely expected that this will happen within the profile where you choose to install Play services. You aren't granting Location 
+ Phone access to Play services so it's unable to provide the location information apps are expecting to get from it.

**Comment by thestinger** [comment]
It works the same way it does on the stock OS in this regard. When Play services is available, apps will use it that would otherwise fall back to using the OS APIs. They want the enhanced features offered by Play services when it's there but often have support for using a different approach. Regardless of whether you grant location access to Play services, by granting it to an app like Tinder you've granted it to the client-side library portion of Play services anyway.

You can use foreground Location access rather than needing background since we have it using foreground services as part of the compatibility layer so it won't be able to use it when the profile as a whole isn't in the foreground or if the foreground services aren't active like any other app.

**Comment by cedws** [comment]
Having a similar problem with GPS/Location in certain apps with the sandboxed Play Services installed.

@thestinger I have granted Location access at all times to "Google Play services" as you described above but no luck (restarted the device too to be sure). I was expecting to see "Google Services Framework" under Location too but it isn't there.

I found this in ADB logs, seems pertinent:

```
09-11 13:25:13.865  1477  2577 W ActivityManager: Appop Denial: Accessing service com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService from pid=3128, uid=10166 requires appop COARSE_LOCATION
```

**Comment by thestinger** [comment]
Did you also give that to the app?

**Comment by cedws** [comment]
Yes.

**Comment by thestinger** [comment]
Can you try giving background access to Google Maps itself just to see if that works around this? I wonder if it's because it does it from a background service or something weird like that.

**Comment by cedws** [comment]
So it's able to track my orientation now, but I'm not sure if that's just a fluke. Changing Location access back to foreground-only doesn't make orientation tracking *stop* working.

I've granted full Location access to Maps and Play Services now. What I'm observing is that it can find my Location when the app is initially opened, but it fails to track movement. Only stopping the app and reopening it moves the location marker.

**Comment by thestinger** [comment]
There are probably still missing shims. Users need to try to get use logs from when it stops working. I don't really have time to go through a bunch of full logs to try to narrow down the time when it's happening and the relevant portion.

**Comment by Tom4tot** [comment]
I had exactly the same issue as https://github.com/GrapheneOS/os-issue-tracker/issues/635#issuecomment-917638569

Installing maps with shelter on the work profile fixes my issue. It can't access play services and so there are no more location issues.

**Comment by zkliebersbach** [comment]
Hi, I'm also having troubles with GPS location in Neuron, an e-scooter rental app. I have a Pixel 3, GrapheneOS version SP1A.210812.015.2021122018. 

I have both WiFi and Bluetooth Location services enabled. Am I correct in thinking you need to have Google Play Services installed just for Location to work?

Couldn't find anything on the docs, any tips? Thanks!

**Comment by codethief** [comment]
I'm experiencing the same issues on my Pixel 5 running GrapheneOS SQ1A.220105.002.2022011009:

- In my private profile (without Google Play Services) all apps requiring location (Osmand, SatStat, GPSLogger, GPSTest) work fine
- In my work/Shelter profile (with Google Play Services with location permission granted), which I use to isolate apps requiring Play Services/FCM, the aforementioned apps still work fine. But all apps which in one way or another use Play Services/FCM (Badoo, Bumble, Couchsurfing, Google Maps, Nextbike, WhatsApp and some others I don't remember) either are not at able to obtain the location at all or they are at most able to obtain a single location fix and stop working afterwards.

What I don't understand is: Shouldn't the Play Services' location API check whether an app has the necessary permissions to obtain the location? If so, how does it do that? I don't see that it has access to app information but then again on normal Android phones (without Play Services sandboxing) it can probably get that information some other way. Could it be that this is the issue here?

**Comment by thestinger** [comment]
I suggest looking at the implementation of the compatibility layer. It reimplements the AppOps checks via the unprivileged AppOps API.

**Comment by thestinger** [comment]
No, that's not the issue. Speculation about this isn't going to help.

**Comment by gordonel** [comment]
Same thing, Pixels 3, 5 and 6

I think it would be great if we could improve the compatibility layer by always feeding Android's native location and sensor data unless Google Location Accuracy is turned on.

I'm open to opening a bounty for this. 0.01 BTC for starters?

**Comment by thestinger** [comment]
There's already active development on both better support for the Play services geolocation service and support for the option to redirect apps to the OS location service which will become the default. Proper support the Play services geolocation service is planned for the next release. Working support for redirection has been developed but will need changes before it can be shipped in a release. You can donate to support GrapheneOS if you want to support our work.

**Comment by flawedworld** [comment]
Solved in 2022013120

**Comment by haary** [comment]
I am still having issues with scooter apps in GrapheneOS build SQ1A.220205.002.2022020800 on Pixel 4a. Sandboxed play services are installed, location services for wifi and bluetooth are activated. Since these apps (Lime and TIER) do rely heavily on location service they do not work at all.

**Comment by haary** [comment]
Google Location Accuracy is enabled
Location Wi-Fi scanning and Bluetooth scanning is on
Use precise location is enabled in app permissions

If any of these is disabled the scooter app complains and refuses to start. With this settings enabled the app accesses the location service (can be seen in the list of apps of recent location services accesses) but it waits forever for the location.

Other apps (e.g. osmand) do find the location immediately.

**Comment by haary** [comment]
I digged a little deeper, the play service itself had no location access permission. So I enabled location permission to play services, rebooted the phone and then it worked.

**Comment by zliebersbach** [comment]
So am I correct in thinking that there is no "mock" API to just proxy Google Play Location Services requests to the devices hardware (GPS)? Is there a separate issue tracking progress on this?

**Comment by thestinger** [comment]
Support for redirecting apps to the OS geolocation service is being developed.

**Comment by zliebersbach** [comment]
@thestinger is there anywhere I can track progress on this feature?

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/981
