### ISSUE TITLE
Battery usage in settings doesn't show usage since full charge

### ISSUE THREAD

**Issue by Khyta** [GrapheneOS/os-issue-tracker#892]
When going into `Settings` > `Battery` > `Battery usage` you can see that the graph doesn't start at 100%. Throughout the day with the battery discharging because of normal usage, the graph also resets (going as low as starting at 12% from my observations) throughout the day.

![Battery usage](https://user-images.githubusercontent.com/33177286/147874929-c63bed0f-e59e-468b-ae21-dab9af544c3f.jpeg)

System info:
- Pixel 6
- Android version 12
- Build number: SQ1D.211205.017.20211122018
- Stable release channel

**Comment by greenerk** [comment]
Chiming here to add another voice to this one.  I used this graph a lot in the past to see if any recently installed apps were chewing through battery overnight.  This is no longer possible as the start of the graph changes randomly.

Pixel 4a
Build SQ1A.211205.008.2021122018
![Screenshot_20220106-163435_1](https://user-images.githubusercontent.com/56622533/148417695-dcd0bec4-3c37-4697-b4d9-c71d5e2b13a5.png)

**Comment by randomhydrosol** [comment]
This seems to be an upstream bug. I had a similar experience on the stock rom

**Comment by thestinger** [comment]
That's likely but it's not properly confirmed.

**Comment by Zanthed** [comment]
Please test if this is still an issue on the newest beta release.

**Comment by snrkl** [comment]
Hey @Zanthed, can you clarify what version is this fixed in? I don't have the ability to run BETA...

**Comment by greenerk** [comment]
I, for one, am still seeing the problem.  The screenshot shows my page. My phone was unplugged, when full, at 07:00. The screenshot is taken 4.5 hours later at 11:30.
The graph still shows truncated line and time which is different during the day.

Pixel 4a
Build SP2A.220305.012.2022030801
![Screenshot_20220317-113002_1](https://user-images.githubusercontent.com/56622533/158813645-dd3171ad-2242-4132-9ffc-6b99f0d5d77a.png)

**Comment by KileXt** [comment]
Hi, 
This is just to confirm the issue on the pixel 5, build number: SP2A.220305.012.2022030801

It hasn't been charged for the last 12hours or something.


![battery_usage_clipped](https://user-images.githubusercontent.com/89696113/159027158-b0048fc6-c1a4-44ec-ab41-f1fac838ad0a.jpg)

**Comment by Zanthed** [comment]
@KileXt reported it was fixed. Other users please test this on the newest beta as well to confirm.

**Comment by snrkl** [comment]
Can confirm this looks fixed on Pixel 5 with SP2A.220305.012.2022032110...

Thanks @thestinger @Zanthed - greatly appreciate your efforts in chasing this one down! :)

**Comment by Khyta** [comment]
Seems to be fixed in Build `SP2A.220305.013.A3.2022032110` for the Pixel 6.

![Uploading Screenshot_20220324-133328.png…]()
